---
- name: installnvidia
  hosts: hostbase
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install packages
      apt:
        state: present
        name: 
                 - nvidia-driver
                 - nvidia-smi
    - name: nvidia.conf
      template:
         src: "templates/nvidia.conf"
         dest: "/etc/modules-load.d/nvidia.conf"
         owner: root
         group: root
         mode: 644
    - name: 70-nvidia.rules
      template:
         src: "templates/70-nvidia.rules"
         dest: "/etc/udev/rules.d/70-nvidia.rules"
         owner: root
         group: root
         mode: 644
    - name: Unconditionally reboot the machine with all defaults
      reboot:
    


