---
- name: Copiar common a /etc/condor/config.d/
  copy:
    src: "files/config/{{ 'gpus' if 'gpu' in group_names else 'cpus' }}/common"
    dest: "/etc/condor/config.d/common"
    mode: '0644'
- name: Ejecutar condor_reconfig
  command: condor_reconfig
  args:
    chdir: "/etc/condor"
