---
- name: Lammps
  hosts: condorexec
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install lammps
      apt:
        name: lammps
        state: present
    - name: install liblammps-dev
      apt:
        name: liblammps-dev
        state: present
