---
- name: Liggghts
  hosts: condorexec
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install liggghts
      apt:
        name: liggghts
        state: present
    - name: install liggghts-dev
      apt:
        name: libliggghts-dev
        state: present
