---
- name: Openfoam
  hosts: condorexec
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install openfoam
      apt:
        name: openfoam2206-default
        state: present
    - name: install openfoam
      apt:
        name: openfoam2306-default
        state: present
