---
- name: Openfoam
  hosts: condorexec
  tasks:
    - name: copy
      copy:
        src: scripts/openfoamrepo.sh
        dest: /root/openfoamrepo.sh
    - name: install repo
      command: ./openfoamrepo.sh
    - name: clear
      command: rm -f openfoamrepo.sh
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install openfoam
      apt:
        name: openfoam2206-default
        state: present
