---
- name: Openfoam
  hosts: condorexec
  tasks:
    - name: copy
      copy:
        src: scripts/openfoamrepo.sh
        dest: /root/openfoamrepo.sh
        mode: '0700'
    - name: install repo
      command: ./openfoamrepo.sh
    - name: clear
      command: rm -f openfoamrepo.sh
