---
- name: Instalar OpenFOAM 8 en Ubuntu 20.04
  hosts: singpu
  tasks:
    - name: Descargar la clave GPG de OpenFOAM
      apt_key:
        url: "https://dl.openfoam.org/gpg.key"
        state: present

    - name: repositorio oficial de OpenFOAM 8
      apt_repository:
        repo: "deb http://dl.openfoam.org/ubuntu focal main"
        state: present

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Instalar OpenFOAM 8
      apt:
        name: openfoam8
        state: present
