---
- name: Instalar OpenFOAM 8 en Ubuntu 20.04
  hosts: condorexec
  tasks:
    - name: Añadir repositorio oficial de OpenFOAM 8
      apt_repository:
        repo: "deb http://dl.openfoam.org/ubuntu"
        state: present

    - name: Añadir la clave del repositorio
      apt_key:
        url: "https://dl.openfoam.org/gpg.key"
        state: present
        
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Instalar OpenFOAM 8
      apt:
        name: openfoam8
        state: present
