---
- name: python
  hosts: condortodo
  tasks:
    - name: python3
      apt:
        name: python3.8-minimal
        state: present
    - name: python-is-python3
      apt:
        name: python-is-python3
        state: present
    - name: python2.7-dev
      apt:    
        name: python2.7-dev
        state: present
    - name: ensure virtualenv
      apt:
        name: virtualenv
        state: present
